# Generated by Django 4.2.11 on 2025-11-04 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("travel_groups", "0003_trippreference"),
    ]

    operations = [
        migrations.CreateModel(
            name="TravelSearch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("destination", models.CharField(max_length=200)),
                ("origin", models.CharField(blank=True, max_length=200, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("adults", models.PositiveIntegerField(default=1)),
                ("rooms", models.PositiveIntegerField(default=1)),
                (
                    "budget_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "budget_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "accommodation_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "activity_categories",
                    models.TextField(
                        blank=True, help_text="Comma-separated list", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_searches",
                        to="travel_groups.travelgroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Travel Search",
                "verbose_name_plural": "Travel Searches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("viewed_results", models.BooleanField(default=False)),
                ("saved_itinerary", models.BooleanField(default=False)),
                ("shared_with_group", models.BooleanField(default=False)),
                ("was_helpful", models.BooleanField(blank=True, null=True)),
                ("feedback_text", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "search",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_entries",
                        to="ai_implementation.travelsearch",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Search History",
                "verbose_name_plural": "Search Histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HotelResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(help_text="ID from external API", max_length=200),
                ),
                ("name", models.CharField(max_length=300)),
                ("address", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "price_per_night",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=10)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("review_count", models.PositiveIntegerField(default=0)),
                ("room_type", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "amenities",
                    models.TextField(
                        blank=True, help_text="Comma-separated list", null=True
                    ),
                ),
                (
                    "distance_from_center",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("breakfast_included", models.BooleanField(default=False)),
                (
                    "cancellation_policy",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "ai_score",
                    models.PositiveIntegerField(
                        blank=True, help_text="AI-generated score (0-100)", null=True
                    ),
                ),
                (
                    "ai_reason",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated reason for recommendation",
                        null=True,
                    ),
                ),
                (
                    "raw_data",
                    models.TextField(
                        blank=True, help_text="Full API response as JSON", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_mock",
                    models.BooleanField(
                        default=False, help_text="Whether this is mock data"
                    ),
                ),
                (
                    "search",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotel_results",
                        to="ai_implementation.travelsearch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hotel Result",
                "verbose_name_plural": "Hotel Results",
                "ordering": ["-ai_score", "total_price"],
            },
        ),
        migrations.CreateModel(
            name="GroupConsensus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "consensus_preferences",
                    models.TextField(
                        help_text="JSON object with consensus preferences"
                    ),
                ),
                (
                    "compromise_areas",
                    models.TextField(
                        blank=True, help_text="JSON list of compromise areas", null=True
                    ),
                ),
                (
                    "unanimous_preferences",
                    models.TextField(blank=True, help_text="JSON list", null=True),
                ),
                (
                    "conflicting_preferences",
                    models.TextField(blank=True, help_text="JSON list", null=True),
                ),
                ("group_dynamics_notes", models.TextField(blank=True, null=True)),
                ("raw_openai_response", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_consensus",
                        to="travel_groups.travelgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group Consensus",
                "verbose_name_plural": "Group Consensuses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FlightResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(help_text="ID from external API", max_length=200),
                ),
                ("airline", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("departure_time", models.DateTimeField()),
                ("arrival_time", models.DateTimeField()),
                ("duration", models.CharField(max_length=50)),
                ("stops", models.PositiveIntegerField(default=0)),
                ("booking_class", models.CharField(default="Economy", max_length=50)),
                (
                    "seats_available",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "ai_score",
                    models.PositiveIntegerField(
                        blank=True, help_text="AI-generated score (0-100)", null=True
                    ),
                ),
                (
                    "ai_reason",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated reason for recommendation",
                        null=True,
                    ),
                ),
                (
                    "raw_data",
                    models.TextField(
                        blank=True, help_text="Full API response as JSON", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_mock",
                    models.BooleanField(
                        default=False, help_text="Whether this is mock data"
                    ),
                ),
                (
                    "search",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flight_results",
                        to="ai_implementation.travelsearch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flight Result",
                "verbose_name_plural": "Flight Results",
                "ordering": ["-ai_score", "price"],
            },
        ),
        migrations.CreateModel(
            name="ConsolidatedResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        help_text="AI-generated summary of recommendations"
                    ),
                ),
                ("budget_analysis", models.TextField(blank=True, null=True)),
                ("itinerary_suggestions", models.TextField(blank=True, null=True)),
                ("warnings", models.TextField(blank=True, null=True)),
                (
                    "recommended_flight_ids",
                    models.TextField(
                        blank=True,
                        help_text="JSON list of recommended flight IDs with scores",
                        null=True,
                    ),
                ),
                (
                    "recommended_hotel_ids",
                    models.TextField(
                        blank=True,
                        help_text="JSON list of recommended hotel IDs with scores",
                        null=True,
                    ),
                ),
                (
                    "recommended_activity_ids",
                    models.TextField(
                        blank=True,
                        help_text="JSON list of recommended activity IDs with scores",
                        null=True,
                    ),
                ),
                (
                    "raw_openai_response",
                    models.TextField(
                        blank=True, help_text="Full OpenAI API response", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "search",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consolidated_result",
                        to="ai_implementation.travelsearch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consolidated Result",
                "verbose_name_plural": "Consolidated Results",
            },
        ),
        migrations.CreateModel(
            name="AIGeneratedItinerary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("destination", models.CharField(max_length=200)),
                ("description", models.TextField(help_text="AI-generated description")),
                ("duration_days", models.PositiveIntegerField()),
                (
                    "selected_activities",
                    models.TextField(
                        blank=True, help_text="JSON list of activity IDs", null=True
                    ),
                ),
                (
                    "estimated_total_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_saved", models.BooleanField(default=False)),
                (
                    "search",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_itineraries",
                        to="ai_implementation.travelsearch",
                    ),
                ),
                (
                    "selected_flight",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="itineraries",
                        to="ai_implementation.flightresult",
                    ),
                ),
                (
                    "selected_hotel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="itineraries",
                        to="ai_implementation.hotelresult",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_itineraries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Generated Itinerary",
                "verbose_name_plural": "AI Generated Itineraries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActivityResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(help_text="ID from external API", max_length=200),
                ),
                ("name", models.CharField(max_length=300)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("duration_hours", models.PositiveIntegerField(default=2)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("review_count", models.PositiveIntegerField(default=0)),
                (
                    "included",
                    models.TextField(
                        blank=True, help_text="What's included", null=True
                    ),
                ),
                (
                    "meeting_point",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("max_group_size", models.PositiveIntegerField(blank=True, null=True)),
                ("languages", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "cancellation_policy",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "ai_score",
                    models.PositiveIntegerField(
                        blank=True, help_text="AI-generated score (0-100)", null=True
                    ),
                ),
                (
                    "ai_reason",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated reason for recommendation",
                        null=True,
                    ),
                ),
                (
                    "raw_data",
                    models.TextField(
                        blank=True, help_text="Full API response as JSON", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_mock",
                    models.BooleanField(
                        default=False, help_text="Whether this is mock data"
                    ),
                ),
                (
                    "search",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_results",
                        to="ai_implementation.travelsearch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Result",
                "verbose_name_plural": "Activity Results",
                "ordering": ["-ai_score", "-rating"],
            },
        ),
    ]
