# Generated by Django 4.2.11 on 2025-11-04 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("travel_groups", "0003_trippreference"),
        ("ai_implementation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupItineraryOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "option_letter",
                    models.CharField(
                        choices=[
                            ("A", "Option A"),
                            ("B", "Option B"),
                            ("C", "Option C"),
                        ],
                        max_length=1,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "description",
                    models.TextField(
                        help_text="AI-generated description of this option"
                    ),
                ),
                (
                    "selected_activities",
                    models.TextField(
                        blank=True, help_text="JSON list of activity IDs", null=True
                    ),
                ),
                (
                    "estimated_total_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "cost_per_person",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "ai_reasoning",
                    models.TextField(
                        help_text="Why AI chose this combination for the group"
                    ),
                ),
                (
                    "compromise_explanation",
                    models.TextField(
                        blank=True,
                        help_text="Which preferences this option balances",
                        null=True,
                    ),
                ),
                ("vote_count", models.PositiveIntegerField(default=0)),
                ("is_winner", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consensus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itinerary_options",
                        to="ai_implementation.groupconsensus",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itinerary_options",
                        to="travel_groups.travelgroup",
                    ),
                ),
                (
                    "search",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="group_options",
                        to="ai_implementation.travelsearch",
                    ),
                ),
                (
                    "selected_flight",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ai_implementation.flightresult",
                    ),
                ),
                (
                    "selected_hotel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ai_implementation.hotelresult",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group Itinerary Option",
                "verbose_name_plural": "Group Itinerary Options",
                "ordering": ["option_letter"],
                "unique_together": {("group", "consensus", "option_letter")},
            },
        ),
        migrations.CreateModel(
            name="ItineraryVote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("voted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Optional comment about their choice",
                        null=True,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_votes",
                        to="travel_groups.travelgroup",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="ai_implementation.groupitineraryoption",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itinerary_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Itinerary Vote",
                "verbose_name_plural": "Itinerary Votes",
                "ordering": ["-voted_at"],
                "unique_together": {("group", "user")},
            },
        ),
    ]
