# Generated by Django 4.2.11 on 2025-11-05 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_implementation", "0002_groupitineraryoption_itineraryvote"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupitineraryoption",
            name="destination",
            field=models.CharField(
                blank=True,
                help_text="Primary destination for this option",
                max_length=200,
                null=True,
            ),
        ),
    ]
