# Generated by Django 4.2.11 on 2025-11-14 09:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai_implementation", "0003_groupitineraryoption_destination"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groupitineraryoption",
            options={
                "ordering": ["round_number", "option_letter"],
                "verbose_name": "Group Itinerary Option",
                "verbose_name_plural": "Group Itinerary Options",
            },
        ),
        migrations.AlterUniqueTogether(
            name="itineraryvote",
            unique_together={("option", "user")},
        ),
        migrations.AddField(
            model_name="groupitineraryoption",
            name="round_number",
            field=models.PositiveIntegerField(
                default=1, help_text="Sequence number for single-option voting flow"
            ),
        ),
        migrations.AddField(
            model_name="groupitineraryoption",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("active", "Active"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="queued",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="itineraryvote",
            name="vote_choice",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="yes", max_length=3
            ),
        ),
    ]
