# Generated by Django 4.2.11 on 2025-11-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_implementation', '0003_groupitineraryoption_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityresult',
            name='raw_data',
        ),
        migrations.RemoveField(
            model_name='flightresult',
            name='raw_data',
        ),
        migrations.RemoveField(
            model_name='hotelresult',
            name='raw_data',
        ),
        migrations.AddField(
            model_name='activityresult',
            name='searched_destination',
            field=models.CharField(blank=True, help_text='Destination this result was searched for', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='flightresult',
            name='searched_destination',
            field=models.CharField(blank=True, help_text='Destination this result was searched for', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotelresult',
            name='searched_destination',
            field=models.CharField(blank=True, help_text='Destination this result was searched for', max_length=200, null=True),
        ),
    ]
