# Generated by Django 4.2.11 on 2025-11-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_implementation", "0004_remove_activityresult_raw_data_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groupitineraryoption",
            options={
                "ordering": ["display_order", "option_letter"],
                "verbose_name": "Group Itinerary Option",
                "verbose_name_plural": "Group Itinerary Options",
            },
        ),
        migrations.AddField(
            model_name="groupitineraryoption",
            name="display_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Order in which options are displayed (0 = not yet shown)",
            ),
        ),
        migrations.AddField(
            model_name="groupitineraryoption",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending - Not yet shown"),
                    ("active", "Active - Currently being voted on"),
                    ("rejected", "Rejected - Did not get unanimous vote"),
                    ("accepted", "Accepted - Got unanimous vote"),
                ],
                default="pending",
                help_text="Current status of this option in the voting process",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="groupitineraryoption",
            name="option_letter",
            field=models.CharField(
                choices=[
                    ("A", "Option A"),
                    ("B", "Option B"),
                    ("C", "Option C"),
                    ("D", "Option D"),
                    ("E", "Option E"),
                    ("F", "Option F"),
                    ("G", "Option G"),
                    ("H", "Option H"),
                    ("I", "Option I"),
                    ("J", "Option J"),
                ],
                max_length=1,
            ),
        ),
    ]
