# Generated by Django 4.2.11 on 2025-11-17 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_implementation', '0005_alter_groupitineraryoption_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelresult',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
