# Generated by Django 4.2.11 on 2025-11-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_implementation", "0006_alter_hotelresult_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityresult",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="External link to activity details or booking page",
                max_length=500,
                null=True,
            ),
        ),
    ]
