# Generated by Django 4.2.11 on 2025-11-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_implementation", "0007_activityresult_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityresult",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="URL to activity image/photo from API",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hotelresult",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="URL to hotel image/photo from API",
                max_length=500,
                null=True,
            ),
        ),
    ]
