# Generated by Django 5.2.7 on 2025-10-18 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='preferencesubmission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='preferencesubmission',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='preferencesubmission',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={},
        ),
        migrations.RemoveField(
            model_name='trip',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='deadline',
        ),
        migrations.AlterField(
            model_name='trip',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
        migrations.DeleteModel(
            name='GroupMember',
        ),
        migrations.DeleteModel(
            name='PreferenceSubmission',
        ),
    ]
