# Generated by Django 5.2.7 on 2025-01-27 00:00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_preferencesubmission_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum budget', max_digits=10, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum budget', max_digits=10, null=True)),
                ('preferred_activities', models.TextField(blank=True, help_text="Activities you'd like to do (comma-separated)")),
                ('avoid_activities', models.TextField(blank=True, help_text="Activities you'd like to avoid (comma-separated)")),
                ('accommodation_type', models.CharField(choices=[('hotel', 'Hotel'), ('airbnb', 'Airbnb'), ('hostel', 'Hostel'), ('resort', 'Resort'), ('camping', 'Camping'), ('no_preference', 'No Preference')], default='no_preference', max_length=50)),
                ('dietary_restrictions', models.TextField(blank=True, help_text='Any dietary restrictions or preferences')),
                ('cuisine_preferences', models.TextField(blank=True, help_text='Preferred cuisines (comma-separated)')),
                ('transportation_preference', models.CharField(choices=[('flight', 'Flight'), ('car', 'Car'), ('train', 'Train'), ('bus', 'Bus'), ('no_preference', 'No Preference')], default='no_preference', max_length=50)),
                ('additional_notes', models.TextField(blank=True, help_text='Any other preferences or requirements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='home.submission')),
            ],
        ),
    ]


