# Generated by Django 4.2.11 on 2025-10-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_groups", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="travelgroup",
            name="destination",
        ),
        migrations.RemoveField(
            model_name="travelgroup",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="travelgroup",
            name="start_date",
        ),
        migrations.AddField(
            model_name="travelgroup",
            name="password",
            field=models.CharField(
                default="",
                help_text="Password required to join the group",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="travelgroup",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Optional group photo",
                null=True,
                upload_to="group_photos/",
            ),
        ),
    ]
