# Generated by Django 4.2.11 on 2025-10-20 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("travel_groups", "0002_remove_travelgroup_destination_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TripPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="Preferred start date for the trip"),
                ),
                (
                    "end_date",
                    models.DateField(help_text="Preferred end date for the trip"),
                ),
                (
                    "destination",
                    models.CharField(help_text="Preferred destination", max_length=200),
                ),
                (
                    "budget",
                    models.CharField(
                        help_text="Budget for the trip (e.g., $1700)", max_length=50
                    ),
                ),
                (
                    "travel_method",
                    models.CharField(
                        choices=[
                            ("flight", "Flight"),
                            ("car", "Car"),
                            ("train", "Train"),
                            ("bus", "Bus"),
                            ("other", "Other"),
                        ],
                        help_text="Preferred method of travel",
                        max_length=20,
                    ),
                ),
                (
                    "rental_car",
                    models.BooleanField(
                        default=False, help_text="Whether rental car is needed"
                    ),
                ),
                (
                    "accommodation_preference",
                    models.CharField(
                        blank=True,
                        help_text="Preferred accommodation type",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "activity_preferences",
                    models.TextField(
                        blank=True, help_text="Preferred activities", null=True
                    ),
                ),
                (
                    "dietary_restrictions",
                    models.TextField(
                        blank=True, help_text="Any dietary restrictions", null=True
                    ),
                ),
                (
                    "accessibility_needs",
                    models.TextField(
                        blank=True,
                        help_text="Any accessibility requirements",
                        null=True,
                    ),
                ),
                (
                    "additional_notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes or preferences",
                        null=True,
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether user has completed entering preferences",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_preferences",
                        to="travel_groups.travelgroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trip Preference",
                "verbose_name_plural": "Trip Preferences",
                "ordering": ["-created_at"],
                "unique_together": {("group", "user")},
            },
        ),
    ]
