name: AI Code Review with ChatGPT

on:
  pull_request:
    paths:
      - "**/*.py"
      - "**/*.html"
      - "**/*.css"
      - "**/*.sh"
      - "**/*.yml"
      - "**/*.yaml"
      - ".github/workflows/ai-code-review.yml"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ai-review-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  review:
    name: Review changes with OpenAI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Optional: show basic diff stats in the run log
      - name: Show changed files
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1 || true
          git diff --name-status origin/${{ github.base_ref }}... | sed -e 's/^/  /' || true

      # Main review
      - name: AI Code Review
        uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_ENDPOINT: https://api.openai.com/v1

          MODEL: "gpt-4o-mini"
          PROMPT: |
            Please review the Python/Django code changes and provide feedback on:
              1) Code quality and Django best practices
              2) Potential bugs/issues
              3) Security concerns 
              4) Performance considerations
              5) Suggestions for improvement
              Keep comments concise and reference line numbers where useful.

          max_completion_tokens: "8000"
          top_p: "1"
          temperature: "0.7"
