name: AI Code Review

on:
  pull_request:
    # Only run when code or docs likely to be reviewed have changed
    paths:
      - "**/*.py"
      - "**/*.md"
      - "**/*.html"
      - ".github/workflows/ai-code-review.yml"
  workflow_dispatch: # allow manual runs from the Actions tab
    inputs:
      paths:
        description: List of glob patterns for files to review
        required: false
        default: |
          **/*.py
          **/*.md
          **/*.html
          .github/workflows/ai-code-review.yml

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ai-review-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  review:
    name: Review changes with OpenAI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Main review
      - name: AI Code Review
        uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_ENDPOINT: https://api.openai.com/v1
          # If you set secret OPENAI_MODEL (e.g., 'gpt-5'), it will use that; else it falls back.
          MODEL: gpt-4
          PROMPT: |
            Please review the Python/Django code changes and provide feedback on:
              1) Code quality and Django best practices
              2) Potential bugs/issues
              3) Security concerns
              4) Performance considerations
              5) Suggestions for improvement
              Keep comments concise and reference line numbers where useful.
          # Newer models expect 'max_completion_tokens' rather than 'max_tokens'
          max_completion_tokens: "8000"
          top_p: "1"
          temperature: "0.7"
