name: AI Code Review

on:
  pull_request:
    # Only run when code or docs likely to be reviewed have changed
    paths:
      - "**/*.py"
      - "**/*.md"
      - "**/*.html"
      - ".github/workflows/ai-code-review.yml"
  workflow_dispatch: # allow manual runs from the Actions tab

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ai-review-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  review:
    name: Review changes with OpenAI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Optional: show basic diff stats in the run log
      # - name: Show changed files
      #   run: |
      #     git fetch origin ${{ github.base_ref }} --depth=1 || true
      #     git diff --name-status origin/${{ github.base_ref }}... | sed -e 's/^/  /' || true

      # Main review
      - name: AI Code Review
        id: review
        uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_ENDPOINT: https://api.openai.com/v1
          MODEL: ${{ secrets.OPENAI_MODEL != '' && secrets.OPENAI_MODEL || 'gpt-4o-mini' }}
          PROMPT: |
            Please review the Python/Django code changes and provide feedback on:
              1) Code quality and Django best practices
              2) Potential bugs/issues
              3) Security concerns
              4) Performance considerations
              5) Suggestions for improvement
              Keep comments concise and reference line numbers where useful.
        with:
          output-file: review-comments.txt

      # Save Review Comments
      - name: Save Review Comments
        id: save_review
        run: |
          echo "REVIEW_COMMENTS<<EOF" >> $GITHUB_ENV
          cat review-comments.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        shell: bash

      # Post Review Comments
      - name: Post Review Comments
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            AI Code Review Results:
            $(cat review-comments.txt)
